### ISSUE TITLE
Crash on my computer

### ISSUE THREAD

**Issue by JBBUCAMP** [DavidArayan/EzySlice-Example-Scenes#1]
hi , your sample crash on my computer.

I have Macbook pro  with Sierra and i use Unity 2017.1.0

Regards

**Comment by DavidArayan** [comment]
Greetings,

You will need to be more specific for me to be able to help you out. Describe the nature of your crash, provide error logs, give me samples or anything needed to be able to debug properly.

Thanks.

**Comment by DavidArayan** [comment]
Since there is no reply for 3 or more days and I cannot replicate, I'm closing this issue.

**Comment by JBBUCAMP** [comment]
can you wait , for me to provide more informations ?

Unity totally crash , i dont have time yet for check the log again but i d like to make it work

**Comment by DavidArayan** [comment]
That's fine,

Please reply here when you get more information and I'll be happy to re-open the issue and take a look, cheers.
